---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: portertech-blog-bastion
spec:
  selector:
    matchLabels:
      app: portertech-blog-bastion
  serviceName: portertech-blog-bastion
  replicas: 3
  template:
    metadata:
      labels:
        app: portertech-blog-bastion
    spec:
      terminationGracePeriodSeconds: 10
      securityContext:
        fsGroup: 42
      containers:
      - name: portertech-blog-bastion
        image: portertech/portertech:latest
        args:
        - --peer
        - habitat-bastion.default.svc.cluster.local
        - --topology
        - leader
        env:
          - name: HAB_LICENSE
            value: accept-no-persist
        ports:
        - name: http
          containerPort: 8000
      - name: sensu-agent
        image: sensu/sensu:5.6.0
        command: ["/opt/sensu/bin/sensu-agent", "start", "--log-level", "debug"]
        env:
          - name: SENSU_BACKEND_URL
            value: ws://sensu.sensu-system.svc.cluster.local:8081
          - name: SENSU_NAMESPACE
            value: kubernetes
          - name: SENSU_SUBSCRIPTIONS
            value: portertech-blog-bastion
          - name: SENSU_KEEPALIVE_INTERVAL
            value: "5"
          - name: SENSU_KEEPALIVE_TIMEOUT
            value: "10"
          - name: SENSU_DEREGISTER
            value: "true"
          - name: SENSU_STATSD_EVENT_HANDLERS
            value: statsd
---
kind: Service
apiVersion: v1
metadata:
  name: portertech-blog-bastion
spec:
  selector:
    app: portertech-blog-bastion
  ports:
  - protocol: TCP
    port: 8000
    targetPort: 8000
  type: LoadBalancer
