api_version: core/v2
type: Handler
metadata:
  namespace: kubernetes
  name: pagerduty
spec:
  type: pipe
  runtime_assets:
  - sensu-pagerduty-handler
  command: sensu-pagerduty-handler --token 'SECRET'
  timeout: 30
  filters:
  - is_incident
  - not_silenced
