api_version: core/v2
type: CheckConfig
metadata:
  namespace: kubernetes
  name: node-prometheus
spec:
  runtime_assets:
  - prometheus-collector
  command: sensu-prometheus-collector -exporter-url http://$HOST_IP:9100/metrics
  subscriptions:
  - daemonset
  publish: true
  interval: 10
  output_metric_format: influxdb_line
  output_metric_handlers:
  - influxdb
